window.QUIZ_QUESTIONS = [
  // 前56题按七个维度交错呈现，避免连续题目暴露测量方向。
  {id:1,dimension:'E',type:'scale',text:'朋友说“没事”，但语气和平时不太一样时，我通常会先观察一下，再决定要不要继续追问。'},
  {id:9,dimension:'A',type:'scale',text:'重要场合前，我会根据“要见什么人、做什么事”来决定自己的整体状态，而不只是穿自己最喜欢的。'},
  {id:17,dimension:'S',type:'scale',text:'刚进入一个陌生群体时，我会留意谁和不同的人都能自然说上话，而不只看谁最活跃。'},
  {id:25,dimension:'W',type:'scale',text:'接到一个要求很模糊的任务时，我通常会先定出第一个可交付的东西，而不是等信息完全齐全。'},
  {id:33,dimension:'C',type:'scale',text:'看到条件和我接近的人明显往前走了一步，我通常会重新评估自己是不是也该争取更多。'},
  {id:41,dimension:'R',type:'scale',text:'做重要选择时，我会问自己：“这个方案要成立，哪些条件必须真的存在？”'},
  {id:49,dimension:'L',type:'scale',text:'开始一件新事情前，我经常会先看看有没有现成工具、平台、数据或别人已经走过的路径可以利用。'},

  {id:2,dimension:'E',type:'scale',text:'一场对话里，如果某个话题一出现气氛就变了，我通常会记住这个变化，而不是只关注对方说了什么。'},
  {id:10,dimension:'A',type:'scale',text:'时间很赶时，我也会优先保证整洁、合身和场合匹配，而不是觉得“反正别人不会注意”。'},
  {id:18,dimension:'S',type:'scale',text:'认识一个以后可能有合作价值的人后，我通常会等到有合适理由时再主动联系，而不是完全等对方想起我。'},
  {id:26,dimension:'W',type:'scale',reverse:true,text:'如果一件事没有明确截止日期，即使我知道它重要，也很容易一直往后放。'},
  {id:34,dimension:'C',type:'scale',text:'两个工作机会条件差不多时，我会明显在意哪个位置三年后的上升空间更大。'},
  {id:42,dimension:'R',type:'scale',text:'别人给出一个听起来很合理的解释时，我还是会顺便想一下：这个决定对他本人有什么实际好处。'},
  {id:50,dimension:'L',type:'scale',reverse:true,text:'遇到需要协作的事情时，我常觉得沟通和分工反而更慢，自己做最省事。'},

  {id:3,dimension:'E',type:'scale',text:'发生分歧时，我会留意对方究竟是在反对事情本身，还是更在意被忽视、被否定或失去控制感。'},
  {id:11,dimension:'A',type:'scale',reverse:true,text:'头像、履历照片或公开主页只要内容没错，我通常不会因为形象已经过时而专门去更新。'},
  {id:19,dimension:'S',type:'scale',reverse:true,text:'和一个人很久没联系后，即使现在有合理的事情想请教，我也会因为尴尬而放弃联系。'},
  {id:27,dimension:'W',type:'scale',text:'几件事同时变得紧急时，我更倾向先确定“今天必须完成的一个结果”，再处理其他事项。'},
  {id:35,dimension:'C',type:'scale',reverse:true,text:'如果收入和生活已经过得去，我通常不会再花太多心力考虑职位、影响力或更高层级的机会。'},
  {id:43,dimension:'R',type:'scale',reverse:true,text:'当身边大多数我信任的人都看好一个机会时，我通常不会再花很多时间建立自己的判断标准。'},
  {id:51,dimension:'L',type:'scale',text:'如果一个付费工具能稳定省下大量重复时间，只要回报算得过来，我愿意花钱换效率。'},

  {id:4,dimension:'E',type:'scale',reverse:true,text:'只要对方嘴上已经答应了，我一般不会再判断他是不是其实有顾虑或只是不好意思拒绝。'},
  {id:12,dimension:'A',type:'scale',text:'进入一个我不熟悉的环境前，我会先观察这里的人通常怎样穿、怎样表达，再决定自己要不要调整。'},
  {id:20,dimension:'S',type:'scale',text:'有人向我求助时，我通常能比较快想到“谁适合帮这件事”，同时也会考虑这样开口会不会消耗关系。'},
  {id:28,dimension:'W',type:'scale',reverse:true,text:'压力一大时，我容易同时打开很多事情来处理，最后真正完成的反而不多。'},
  {id:36,dimension:'C',type:'scale',text:'如果一个机会能明显提高未来选择权，我可以接受它短期更累、要求更高或结果更不确定。'},
  {id:44,dimension:'R',type:'scale',text:'看到一个人非常成功时，我更想知道他的起点、行业阶段和关键条件，而不是直接照抄他的做法。'},
  {id:52,dimension:'L',type:'scale',text:'如果换到更好的平台或环境长期价值明显更高，我愿意承担一段适应期和必要成本。'},

  {id:5,dimension:'E',type:'scale',text:'同一句话面对不同的人，我会自然调整说法；我更在意对方会怎样接收，而不只是自己有没有表达清楚。'},
  {id:13,dimension:'A',type:'scale',text:'如果某种穿着或表达方式很舒服，但在关键场合明显削弱专业感，我通常会换一种。'},
  {id:21,dimension:'S',type:'scale',reverse:true,text:'在一个新团队里，我通常要等别人明确告诉我，才会知道谁的意见其实最有影响力。'},
  {id:29,dimension:'W',type:'scale',text:'一件事结果不理想后，我会至少改掉下一次流程里的一个具体环节，而不只是总结原因。'},
  {id:37,dimension:'C',type:'scale',text:'需要谈薪、争取名额或表达晋升意愿时，只要我认为条件够，我更倾向明确提出，而不是等别人主动安排。'},
  {id:45,dimension:'R',type:'scale',text:'看到“免费”“限时”“大家都在用”这类信息时，我会顺手想一下提供方到底通过什么获益。'},
  {id:53,dimension:'L',type:'scale',text:'在请别人帮忙前，我通常会先想自己能提供什么，让这次合作不只是单向索取。'},

  {id:6,dimension:'E',type:'scale',reverse:true,text:'我有时会到事情结束以后才意识到，某个人当时其实已经明显不舒服或被冷落了。'},
  {id:14,dimension:'A',type:'scale',reverse:true,text:'我很少注意到合身程度、姿态、声音状态这些细节会怎样改变一个人的第一印象。'},
  {id:22,dimension:'S',type:'scale',text:'我会把少数重要关系当作需要长期维护的事情，而不是只有需要帮忙时才联系。'},
  {id:30,dimension:'W',type:'scale',reverse:true,text:'我经常会对新想法很兴奋，但真正做到可以交付或公开的比例没有那么高。'},
  {id:38,dimension:'C',type:'scale',reverse:true,text:'即使一个机会回报很高，只要竞争者很多、输赢很明确，我也常会下意识想避开。'},
  {id:46,dimension:'R',type:'scale',reverse:true,text:'只要一个选择短期效果很好，我通常不会再花太多时间考虑它长期可能带来的代价。'},
  {id:54,dimension:'L',type:'scale',reverse:true,text:'碰到自己不会的问题时，我第一反应通常还是先一个人研究，很少马上寻找能借用的资源。'},

  {id:7,dimension:'E',type:'scale',text:'需要说一件可能让人不舒服的事时，我会考虑“什么时候说、用什么方式说”会比只考虑内容本身更重要。'},
  {id:15,dimension:'A',type:'scale',text:'如果某项外在投入能长期改善我在工作、社交或约会中的状态，我会把它当作正常预算，而不是纯消费。'},
  {id:23,dimension:'S',type:'scale',text:'遇到一个自己解决很慢的问题时，我脑子里通常会出现几位“也许可以问一下”的人。'},
  {id:31,dimension:'W',type:'scale',text:'如果别人依赖我的交付，我发现可能延期时通常会提前说明，并给出新的时间或方案。'},
  {id:39,dimension:'C',type:'scale',text:'我会定期留意自己的收入、职位、影响范围或选择权有没有实质增长，而不只看自己是不是很忙。'},
  {id:47,dimension:'R',type:'scale',text:'面对一个看起来不错的机会，我会同时问自己：“选它以后，我会失去什么时间和其他可能性？”'},
  {id:55,dimension:'L',type:'scale',text:'如果两个人各自做只能得到普通结果，但组合起来明显更强，我通常愿意重新设计分工和利益安排。'},

  {id:8,dimension:'E',type:'scale',reverse:true,text:'我更喜欢别人把需求直接说清楚；如果需要我从语气、表情或关系变化里猜，我会觉得很低效。'},
  {id:16,dimension:'A',type:'scale',reverse:true,text:'我不太喜欢思考“别人第一眼会怎么看我”，因此也很少为了不同场合调整自己的呈现。'},
  {id:24,dimension:'S',type:'scale',reverse:true,text:'即使认识合适的人，我也常因为不想欠人情，而避免请对方介绍、推荐或牵线。'},
  {id:32,dimension:'W',type:'scale',reverse:true,text:'一件事情过了最初的新鲜感以后，如果没有外界催促，我的推进速度通常会明显下降。'},
  {id:40,dimension:'C',type:'scale',text:'如果我确认当前环境的成长上限已经很低，我会给自己设一个时间点，认真准备下一步。'},
  {id:48,dimension:'R',type:'scale',text:'规则很复杂时，我会尝试找出真正影响结果的两三个变量，而不是平均用力理解所有细节。'},
  {id:56,dimension:'L',type:'scale',reverse:true,text:'即使我知道某个人或某个平台可能帮得上忙，我也常常拖到自己实在解决不了才会去调用。'},

  // 57-68为强制选择题。mOption明确雄竞侧选项，A/B方向刻意交错，避免通过选项位置猜测结果。
  {id:57,type:'binary',weight:2,mOption:'A',text:'一个重要项目只能选一种角色，你更愿意承担：',a:'负责最关键、最难替代的核心成果，最终结果可以直接证明我的能力。',b:'负责把关键人物和资源协调到一起，让项目因为我更容易推进。'},
  {id:58,type:'binary',weight:1,mOption:'B',text:'进入一个高质量的新环境，一小时以后你更希望留下哪种印象？',a:'“和这个人相处很舒服，以后愿意再见，也愿意把他介绍给别人。”',b:'“这个人判断很准、能解决问题，以后有重要事情可以找他。”'},
  {id:59,type:'binary',weight:1,mOption:'B',text:'遇到一个明显比你强的竞争者，你更可能先做什么？',a:'换一个更适合自己的位置，让对方的优势不再是决定胜负的关键。',b:'找出差距最大的环节，集中提升到可以正面比较。'},
  {id:60,type:'binary',weight:2,mOption:'A',text:'假设三年后只能看到一种明显变化，你更希望是：',a:'收入、职位、业务或自己拥有的资产明显上了一个台阶。',b:'自己所处的社交、生活和长期关系环境明显上了一个台阶。'},
  {id:61,type:'binary',weight:2,mOption:'B',text:'如果突然去一个完全陌生的城市重新开始，你更希望先拥有：',a:'很快建立可信关系、获得信息和支持的能力。',b:'不依赖熟人也能马上创造收入或职业价值的能力。'},
  {id:62,type:'binary',weight:1,mOption:'B',text:'一个机会需要别人愿意把你推到更核心的位置，你会更想先准备：',a:'让关键的人更了解我、信任我，并愿意为我背书。',b:'拿出足够硬的成果，让“为什么是我”变得很难反驳。'},
  {id:63,type:'binary',weight:3,mOption:'B',text:'面对一个名额很少、很多人都想要的机会，你更倾向：',a:'先理解谁在做决定，并提高自己被优先考虑的概率。',b:'把评价标准研究清楚，然后尽量在标准上做到更强。'},
  {id:64,type:'binary',weight:2,mOption:'A',text:'哪一种状态会让你更有安全感？',a:'即使环境和关系全部变化，我仍能凭自己的能力重新站住。',b:'即使环境全部变化，我也能很快重新建立关系和支持网络。'},
  {id:65,type:'binary',weight:2,mOption:'B',text:'如果今年只有一笔额外预算可以投自己，你更愿意把大部分放在：',a:'形象、表达、社交场景和高质量连接上。',b:'专业训练、生产工具、商业能力或能形成资产的项目上。'},
  {id:66,type:'binary',weight:3,mOption:'B',text:'一个高压项目里，你更愿意被大家依赖的是：',a:'我能让关键的人愿意合作、减少摩擦，并把关系维持住。',b:'最难的结果交给我，我能把它真正做出来。'},
  {id:67,type:'binary',weight:1,mOption:'B',text:'第一次进入一个资源密度很高的场合，你更容易优先观察：',a:'谁和谁熟、谁被信任、信息和关系是怎么流动的。',b:'谁能拍板、大家真正缺什么、什么结果最有价值。'},
  {id:68,type:'binary',weight:2,mOption:'A',text:'如果只能长期建立一种“别人很难拿走”的优势，你更想要：',a:'一套可迁移的能力、成果或资产，让我到哪里都能创造价值。',b:'一种稳定的综合吸引和关系价值，让优质的人和机会更愿意靠近我。'},

  {id:69,dimension:'K69',type:'scale',text:'即使没有人知道，我仍愿意把时间投入到以后换环境也能带走的能力上。'},
  {id:70,dimension:'K70',type:'scale',text:'如果一件事长期看不到成长、现实收益或重要体验，我会重新评估，而不是因为已经投入很多就继续。'},
  {id:71,dimension:'K71',type:'scale',text:'我既希望自己真的有能力，也希望在关键场合别人能够准确感知到这种能力。'},
  {id:72,dimension:'K72',type:'scale',text:'只要效果和风险相近，我更愿意采用省时间、可复制的方法，而不是为了证明自己而亲自完成每一步。'}
];
